### ISSUE TITLE
Notes text box make larger request

### ISSUE THREAD

**Issue by jwilson1008** [alberiv/pwsafe#1]
Thanks for your work on this.  Is there any way you could make the notes section for each password safe entry longer?  I keep many notes with each entry and noticed they are being truncated because the text box can handle that many characters.  Thanks.

**Comment by mastroalbert** [comment]
Yes of course if it’s a textbox problem it can be fixed easily. If it’s a Iimitation of the original password safe, I won't add it because it’d take too much time.
I also want to add keyboard shortcut to quickly navigate to group letters, so I can make a release to add both. Give me some days.

Thanks for your feedback

________________________________

**Comment by jwilson1008** [comment]
Thanks for quick reply! As far as the limitations regarding the original password safe, at least all the windows desktop versions up to the current one don't seem to have the limitation so, hopefully it is just a text box modification.  Thanks!

**Comment by albertorivelli** [comment]
Ok I checked and there's no limit in the textbox itself. If you use a text longer than 30000 characters my version of Password safe which is 3.31 (5298) (I know it's quite old) shows a pop-up that warns you that the text will be truncated to 30000. Then I tried opening it with the app and all the text truncated to 30000 is shown correctly.
Attached is the test db I used, the master password is "password".

[test.zip](https://github.com/albertorivelli/pwsafe/files/1649703/test.zip)

**Comment by mastroalbert** [comment]
Ok I checked and there's no limit in the textbox itself. If you use a text longer than 30000 characters my version of Password safe which is 3.31 (5298) (I know it's quite old but that's the version the app is based on) shows a pop-up that warns you that the text will be truncated to 30000. Then I tried opening it with the app and all the text truncated to 30000 is shown correctly.
Attached is the test db I used, the master password is "password".

[test.zip](https://github.com/albertorivelli/pwsafe/files/1649713/test.zip)

**Comment by mastroalbert** [comment]
As you can see from the following snippet extracted from https://github.com/pwsafe/pwsafe/blob/master/src/ui/Windows/Windowsdefs.h the limit is still there in the latest version.

`// Maximum number of characters that can be added to a MFC CEdit control`
`// by default (i.e. without calling SetLimitText). Note: 30000 not 32K!`
`// Although this limit can be changed to up to 2GB of characters`
`// (4GB memory if Unicode), it would make the database size absolutely enormous!`
`#define MAXTEXTCHARS 30000`

Try to ask the Password safe team about this.
